apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "static-site.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "static-site.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    {{- if .Values.metrics.enabled }}
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: {{ .Values.metrics.port }}
      protocol: TCP
    {{- end }}
