apiVersion: v2
name: threat-api
description: Robert Consulting Threat Intelligence API
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - threat-intelligence
  - mitre-attack
  - fastapi
maintainers:
  - name: Rob Bailey
    email: rsbailey@necron99.org
